[versions]
wiremock = "3.3.1" # WireMock releases: https://github.com/wiremock/wiremock/releases

[libraries]
wiremock-standalone = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
